---
name: "build"

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  collect:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash
    outputs:
      build-matrix: "${{ steps.matrix.outputs.matrix }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create build matrix
        id: matrix
        run: |
          ./bin/build_matrix.py

  build:
    name: Build Linux Documents
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash
    needs: collect
    strategy:
      matrix:
        include: "${{ fromJSON(needs.collect.outputs.build-matrix) }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add directory to safe dir overrides
        run: |
          git config --global --add safe.directory "$PWD"

      - name: Build ${{ matrix.device }}
        run: |
          make DEVFAMILY=${{ matrix.device }} OS=${{ matrix.os }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-${{ matrix.os }}
          path: build/
          retention-days: 1
