---
name: "check_toc_txt"

on:
  pull_request:
    branches: [master]
    paths:
      - 'source/**'
      - 'configs/*/*_toc.txt'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update refs and settings
        run: |
          git config --global --add safe.directory "$PWD"
          git switch -C pr
          git fetch --no-tags --depth=1 origin master
          git switch master

      - name: Run rstcheck
        run: |
          # Disable color output
          export NO_COLOR=true

          # Run the test
          bin/delta.sh -a master -b pr -- ./bin/check_toc_txt.py

          # Prepare summary
          WARNING_COUNT=$(wc -l < _new-warn.log)
          if [ "$WARNING_COUNT" -gt "0" ]; then
            echo "New issues found with check_toc_txt.py:"
            echo '```text'
            cat _new-warn.log
            echo '```'
          else
            echo "No new issues found with check_toc_txt.py"
          fi >> "$GITHUB_STEP_SUMMARY"

          # Prepare the artifacts
          mkdir -p ./results
          echo "${{ github.event.number }}" > ./results/id
          cp "$GITHUB_STEP_SUMMARY" ./results/summary
          echo "$(wc -l < _new-warn.log)" > ./results/problem-count

          # Exit with error if there are new warnings
          [ "$WARNING_COUNT" -eq "0" ]

      - name: Save results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: results/
          retention-days: 1
