---
name: Commit Check
on:
  pull_request:
    branches: ['master']

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check commit
        uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: true
          author-name: true
          author-email: true
          commit-signoff: true
          job-summary: true
          pr-comments: true
