---
name: "deploy"

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  agregate:
    name: Agregate build artifacts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add directory to safe dir overrides
        run: |
          git config --global --add safe.directory "$PWD"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: build
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}

      - name: Generate root index
        run: ./bin/root_index.py

      - name: Upload static files as single artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: agregate
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Update github page deployment
        uses: actions/deploy-pages@v4
